version: "3.5"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
    networks:
      - network_services

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - network_services

networks:
  network_services: {}